from asq_solvers.service.predictors.decompatt_qa_predictor import DecompAttPredictor
from asq_solvers.service.predictors.dgem_predictor import DgemPredictor
from asq_solvers.service.predictors.bidaf_qa_predictor import BidafQaPredictor
