from arc_solvers.service.predictors.decompatt_qa_predictor import DecompAttPredictor
from arc_solvers.service.predictors.dgem_predictor import DgemPredictor
from arc_solvers.service.predictors.bidaf_qa_predictor import BidafQaPredictor
